import AppLayout from '@/components/Layout'

import type {Metadata} from 'next'

import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AppLayout>
      {/* <Nav /> */}
      <nav className="text-center leading-12 h-24 bg-linear-to-br from-seasalt-100 via-seasalt-200 to-seasalt-300 text-transparent! text-3xl bg-clip-text">
        This layout is shared between all the page routes inside (birds)
        namespace
      </nav>
      {children}
    </AppLayout>
  )
}
