import {Geist, Geist_Mono} from 'next/font/google'

import '../globals.css'
import AppLayout from '@/components/Layout'

import type {Metadata} from 'next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppLayout>
          {/* <Nav /> */}
          <nav className="text-center leading-12 h-24 bg-linear-to-br from-seasalt-100 via-seasalt-200  to-seasalt-300 text-transparent! text-3xl bg-clip-text">
            This layout is shared between all the page routes inside (store)
            namespace
          </nav>
          <main id="body">{children}</main>
        </AppLayout>
      </body>
    </html>
  )
}
