import type {Metadata} from 'next'
import '../globals.css'
import AppLayout from '@/components/Layout'
import SpeakyProvider from '@/context/Speaky'
import ReaderNav from './Nav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AppLayout>
      <SpeakyProvider>
        <>
          <ReaderNav />
          {children}
        </>
      </SpeakyProvider>
    </AppLayout>
  )
}
